services:
  scylla-node1:
    container_name: scylla-node1
    image: scylladb/scylla:latest
    restart: always
    command:
      - --seeds=scylla-node1
      - --smp=1
      - --memory=750M
      - --alternator-port=8000
      - --alternator-write-isolation=always
      - --experimental-features=alternator-streams
    ports:
      - 8000:8000
      - 9042:9042

  scylla-node2:
    container_name: scylla-node2
    image: scylladb/scylla:latest
    restart: always
    command:
      - --seeds=scylla-node1
      - --smp=1
      - --memory=750M
      - --alternator-port=8000
      - --alternator-write-isolation=always
      - --experimental-features=alternator-streams
    ports:
      - 8001:8000
      - 9043:9042

  scylla-node3:
    container_name: scylla-node3
    image: scylladb/scylla:latest
    restart: always
    command:
      - --seeds=scylla-node1
      - --smp=1
      - --memory=750M
      - --alternator-port=8000
      - --alternator-write-isolation=always
      - --experimental-features=alternator-streams
    ports:
      - 8002:8000
      - 9044:9042
