[package]
name = "cdc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.96"
async-trait = "0.1.86"
futures = "0.3.31"
scylla = "0.13.1"
scylla-cdc = "0.2.0"
tokio = { version = "1.43.0", features = ["full"] }
